### ISSUE TITLE
RSS feed on packages website has links with missing root slash

### ISSUE THREAD

**Issue by jputcu** [nim-lang/packages#1410]
I've subscribed to the RSS feed for new packages on the https://nimble.directory/ but noticed that when clicking on a link, I get sent to e.g. `https://nimble.directory/https:/nimble.directory/pkg/nimbug`.
The reason appears to be the link urls are missing an extra slash at the root.
`<link>https:/nimble.directory/pkg/nimbug</link>`.

**Comment by narimiran** [comment]
cc @FedericoCeratto

**Comment by jputcu** [comment]
See
Duplicate of https://github.com/FedericoCeratto/nim-package-directory/issues/27
