### ISSUE TITLE
Orient package is incorrect

### ISSUE THREAD

**Issue by Yardanico** [nim-lang/packages#1549]
See https://github.com/philip-wernersbach/nim-orient - the code is in the `prerelease` branch which is NOT the default, also it's not specified in Nimble (can we even specify a branch in packages.json? If so, I'll make a PR to fix this one).

Running `nimble install orient` you'll get:
```
~/P/n/pkgraph ❯❯❯ nimble install orient
Downloading https://github.com/philip-wernersbach/nim-orient using git
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Specified directory (/tmp/nimble_5457/githubcom_philipwernersbachnimorient) does not contain a .nimble file.
```

P.S.: Found when working with my pkgraph "project".

**Comment by dom96** [comment]
CC @philip-wernersbach

**Comment by Yardanico** [comment]
Still an issue

**Comment by dom96** [comment]
feel free to fix it

**Comment by Yepoleb** [comment]
Not an issue with the package list and it's unlikely the author will ever fix this.
