### ISSUE TITLE
Package libsaedea README.md file not loaded on nimble.directory

### ISSUE THREAD

**Issue by m33m33** [nim-lang/packages#1873]
There is a README.md file in the GIT depot, a DOC section on the package.json description, but the libsaedea page on nimble.directory is empty and says "Package libsaedea doesn't contains a README file."

How can I fix this ?
<img width="1196" alt="Capture d’écran 2021-04-18 à 19 55 52" src="https://user-images.githubusercontent.com/13889580/115155453-52c78e80-a080-11eb-98e9-b8cdda77182d.png">

(see [https://git.qoto.org/m33/libsaedea/-/blob/master/README.md](https://git.qoto.org/m33/libsaedea/-/blob/master/README.md))

**Comment by SolitudeSF** [comment]
nimble.directory is a 3rd party project https://github.com/FedericoCeratto/nim-package-directory

**Comment by m33m33** [comment]
> nimble.directory is a 3rd party project https://github.com/FedericoCeratto/nim-package-directory

oh ok, I will open an issue there, thanks
