### ISSUE TITLE
Cannot get the correct version of my package

### ISSUE THREAD

**Issue by lorycontixd** [nim-lang/packages#2279]
Yesterday I published my package to nimble, this morning I'm trying to install it from a project, but the wrong version is getting fetched.

![nimbleinstall](https://user-images.githubusercontent.com/56968043/179217687-9e1bb154-756d-43c2-b41f-cde340f7bc87.png)

In my nimble file I have
```
requires "raytracingalgorithm == 2.1.0"
```
What am i doing wrong?
Thanks

**Comment by lorycontixd** [comment]
Nevermind, the nimble file was not up to date. :)

**Comment by lorycontixd** [comment]
That did not fix my issue, I'm still getting the same error

**Comment by narimiran** [comment]
> That did not fix my issue, I'm still getting the same error

Did you do `nimble update` after you updated the version of your package?

**Comment by dom96** [comment]
Your Nimble file is still not up to date. It needs to be up to date on the `v2.1.0` tag: https://github.com/lorycontixd/RaytracingAlgorithm/blob/v2.1.0/RaytracingAlgorithm.nimble#L3

**Comment by Yardanico** [comment]
yeah, @lorycontixd you tagged a 2.1.0 version 7 days ago, and Nimble uses tags if they exist in a repository, so you have to make a new tag or update the existing one.
