### ISSUE TITLE
Can a Nim package be stored in a repository subfolder?

### ISSUE THREAD

**Issue by viferga** [nim-lang/packages#2330]
Hi, my current project has a folder with multiple ports, and it is originally written in C/C++, those ports are just wrappers around the C main API.

Here's the subfolder: https://github.com/metacall/core/tree/develop/source/ports/nim_port

Could be this published as a package if I add the `metacall.nimble` file? Or does it need to be stored in root folder?

**Comment by Yardanico** [comment]
Yes it's possible, one example from the `packages.json`:
```json
  {
    "name": "shaname",
    "url": "https://github.com/Torro/nimble-packages?subdir=shaname",
    "method": "git",
    "tags": [
      "sha1",
      "command-line",
      "utilities"
    ],
    "description": "Rename files to their sha1sums",
    "license": "BSD",
    "web": "https://github.com/Torro/nimble-packages/tree/master/shaname"
  },
  ```

**Comment by Yardanico** [comment]
Just don't forget that Nimble will *only* install the subdirectory then, and not files outside of it.

**Comment by viferga** [comment]
Thank you so much for the fast response! I will PR the package as soon as possible.
