### ISSUE TITLE
Clarify license of packages.json

### ISSUE THREAD

**Issue by Yepoleb** [nim-lang/packages#2522]
If other people want to use or rehost packages.json it would be useful to clarify the license.

**Comment by ringabout** [comment]
It should be MIT.

**Comment by Yepoleb** [comment]
MIT is for software and requires distributing the license together with the software. I'd prefer CC-BY or CC0 because they are better suited for this purpose and don't require distribution of the license.

**Comment by ringabout** [comment]
Fine with me.

**Comment by Araq** [comment]
With me too.

**Comment by Yepoleb** [comment]
I'd go for CC-BY because I see no reason why attribution would be difficult. Should I create a PR for it?

**Comment by Araq** [comment]
Yes, please.
