### ISSUE TITLE
Please withdraw my diff package

### ISSUE THREAD

**Issue by mark-summerfield** [nim-lang/packages#2783]
Could you withdraw my package https://nimble.directory/pkg/diff please?

I don't know how to do this myself.

The reason is that in view of the EU’s Cyber Resilience Act and an abundance of caution, I have withdrawn all my free software (see [EU CRA](https://en.wikipedia.org/wiki/Cyber_Resilience_Act#Criticism)).

**Comment by pietroppeter** [comment]
To do it yourself the only thing you would need to do is to remove the relevant lines in `packages.json` (opening a PR with the change). Otherwise you will have to wait until someone does it for you :)

**Comment by mark-summerfield** [comment]
Thanks, I've done that in PR  #2785
