### ISSUE TITLE
Clarify flagging procedure

### ISSUE THREAD

**Issue by Graveflo** [nim-lang/packages#2809]
The readme says "Non-mature packages should be flagged as such". This sounds a good idea, but I think the odds of it being done are very low if it's not suggested how to do this. I recommend changing the wording to "Non-mature packages should be flagged as such by ..."

Small change, but I imagine that would make a big difference if you want people to actually do that.

**Comment by penguinite** [comment]
I assume the flagging procedure is done by opening an issue here. So that's my PR tries to clarify
