### ISSUE TITLE
Package name scheme

### ISSUE THREAD

**Issue by def-** [nim-lang/packages#361]
Some libraries have names of the scheme `nim-$library` while most are just `$library`. This is annoying when installing a package and you have to try out both. Could we just rename all `nim-$library` packages?

**Comment by dom96** [comment]
It's up to the package owners to rename them. But they will be forced to because dashes are not allowed in package names and this will soon be enforced.

**Comment by def-** [comment]
It's also very annoying when the package name in the packages.json does not fit the internal name of the package. Then it is installed as a dependency every time again. So I believe there should be some enforcement mechanism to make sure the names are consistent.

**Comment by dom96** [comment]
Sure. We will need to add logic to handle package renames first though.

**Comment by andreaferretti** [comment]
I think the simplest course of action is: when a PR is made, skim the package nimble file and check that the name declared there agrees with the one in package.json, otherwise reject the PR. It only takes a few seconds, and PRs are accepted manually anyway

**Comment by dom96** [comment]
Logic for checking whether package names are correct has been implemented (currently as a warning).
