### ISSUE TITLE
Tag naming / checking

### ISSUE THREAD

**Issue by abudden** [nim-lang/packages#399]
Having just started adding my package to the package list, I was looking at the existing tags to see which were most appropriate.  I found a lot of duplication.  A few examples from the start of the alphabet:
- "2d", "2D"
- "authentication", "authenticator"
- "algorithm", "algorithms"
- "app", "application"
- "benchmark", "benchmarking"
- "bind", "binding", "bindings"
- "Bloom", "Bloom filter"

The list goes on (and even includes "Nim", "nim" and "nimrod"!)...

If these tags are ever selected as the means of trying to search/filter packages, it's going to be very hard to actually find anything useful I suspect.

**Comment by Araq** [comment]
Stemming and case insensitive searches are not rocket science... I don't see any problems here.

**Comment by dom96** [comment]
PRs to clean up tags are always welcome!

**Comment by achesak** [comment]
At the very least, can "nim" and "nimrod" be removed as tags? They're rather pointless as every package is going to involve Nim anyway.

**Comment by dom96** [comment]
Sure
