### ISSUE TITLE
Empty package still accepted in repository

### ISSUE THREAD

**Issue by idlewan** [nim-lang/packages#478]
I've noticed that https://gitlab.com/define-private-public/AJAX-Nim/tree/master  (ajax in nimble) is in the list of packages, however it looks like there is no code at all in the repository.

Can we remove it?
Also, it would definitely be better to only add packages that have at least a chance of working. How come this one got through?

**Comment by dom96** [comment]
Sure, we can remove it. Unless @define-private-public objects, looks like he/she was just reserving a name https://github.com/nim-lang/packages/pull/452

**Comment by define-private-public** [comment]
Go ahead.  I never got around to working on the package.  It would be best to free it up.

**Comment by idlewan** [comment]
I didn't know that reserving a package name was a thing.
I was interested in js bindings, and was just mostly baffled when I tried to read the code of the package.

**Comment by dom96** [comment]
It isn't really, but I let it slide. I won't allow it from now on.

Please report any other problematic packages that you see.
