### ISSUE TITLE
Cannot install nim-sndfile

### ISSUE THREAD

**Issue by frarees** [nim-lang/packages#553]
```
$ nimble install nim-sndfile --verbose
    Reading official package list
Downloading https://github.com/julienaubert/nim-sndfile using git
     Error: nim-sndfile is an invalid package name: cannot contain '-'
```

**Comment by dom96** [comment]
You can quickly workaround this by cloning the repo manually and renaming the package yourself, then running ``nimble install`` in the package's directory.

The long term solution is to ask the maintainer to fix their package (better yet create a PR for them) :)

**Comment by dom96** [comment]
Fixed now.
