### ISSUE TITLE
NimBorg no longer being maintained in original repo

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/packages#589]
Hi.

Over in the original repo for NimBorg, the author has mentioned this:

"Sorry chap, I'm not maintaining this repo any more. I'll take it down eventually so that people don't get confused. Note that some core nim devs have forked it, and perhaps other people would keep maintaining it."

https://github.com/micklat/NimBorg/issues/5#issuecomment-332804717

@dom96 - look into that please?

eg, changing packages json file to point to an actively maintained version.

**Comment by dom96** [comment]
I'm not aware of any that are being maintained. If you can find one then please update the packages.json file.

**Comment by wizzardx** [comment]
@genotrance - thanks, that PR and listed features look really interesting. I don't see how it will detect abandoned packages (that eg, no longer compile on latest nim Stable/Dev, or, where automated tests fail), but it sounds like you have some kind of plan for that. I'll close this ticket for now
