### ISSUE TITLE
Package requiring Nim devel

### ISSUE THREAD

**Issue by nitely** [nim-lang/packages#754]
Hey @dom96,
Is it ok to add a package that requires Nim devel? I don't remember seeing one, so I thought I'd ask

**Comment by Yardanico** [comment]
I think it's OK as long as you will tell it in Readme of your project. And example of a library in nimble which requires devel - chronicles

**Comment by Yardanico** [comment]
https://github.com/status-im/nim-chronicles

**Comment by dom96** [comment]
Sure, plenty of packages that require devel. You can (and should) specify the minimum Nim version requirement in your Nimble file.
