### ISSUE TITLE
Found duplicates in packages.json.

### ISSUE THREAD

**Issue by annadess** [nim-lang/packages#954]
Hi, I found a few duplicate packages in the packages.json file. 
You can find them by searching for their url field.
- https://bitbucket.org/BitPuffin/nim-ogg
- https://bitbucket.org/BitPuffin/nim-portaudio
- https://bitbucket.org/BitPuffin/nim-vorbis
- https://github.com/cowboy-coders/nim-libclang.git
- https://github.com/flyx/NimYAML
- https://github.com/fowlmouth/nimrod-chipmunk/

Just thought maybe you should know, maybe this was by mistake?

**Comment by genotrance** [comment]
All these packages have basically claimed both names - package and nim-package. Does this really deserve any action?
